services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      # HTTP Router
      - "traefik.http.routers.portainer.rule=Host(`manager.bwserver.com.br`)"
      - "traefik.http.routers.portainer.entrypoints=web"
      - "traefik.http.routers.portainer.middlewares=portainer-https-redirect"
      # HTTPS Router
      - "traefik.http.routers.portainer-secure.rule=Host(`manager.bwserver.com.br`)"
      - "traefik.http.routers.portainer-secure.entrypoints=websecure"
      - "traefik.http.routers.portainer-secure.tls.certresolver=letsencrypt"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"
      - "traefik.docker.network=traefik"
      # Middleware para redirect HTTPS
      - "traefik.http.middlewares.portainer-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.portainer-https-redirect.redirectscheme.permanent=true"

volumes:
  portainer_data:

networks:
  traefik:
    external: true
