services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./volumes:/etc/automation-webhook/volumes
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./:/var/www/html
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/public
      - DOCKER_HOST=unix:///var/run/docker.sock
    networks:
      - traefik
    privileged: false
    user: "33:999"  # www-data:docker group
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.automation-webhook.rule=Host(`manager.bwserver.com.br`)"
      - "traefik.http.routers.automation-webhook.tls=true"
      - "traefik.http.routers.automation-webhook.tls.certresolver=letsencrypt"
      - "traefik.http.services.automation-webhook.loadbalancer.server.port=80"
    restart: unless-stopped
    depends_on:
      - traefik
  traefik:
    image: traefik:v3.0
    container_name: traefik
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./traefik/acme.json:/acme.json:ro
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`traefik.bwserver.com.br`)"
      - "traefik.http.routers.dashboard.tls=true"
      - "traefik.http.routers.dashboard.tls.certresolver=letsencrypt"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.middlewares=auth"
      # - "traefik.http.middlewares.auth.basicauth.users=admin:$apr1$Ud6F0kKu$SlTIBkNtSEZWL3IpEW7co/"
    environment:
      - TRAEFIK_LOG_LEVEL=INFO
    security_opt:
      - no-new-privileges:true
networks:
  traefik:
    external: true