services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    volumes:
      - /etc/automation-webhook:/etc/automation-webhook
      - /var/run/docker.sock:/var/run/docker.sock:ro