services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./volumes:/var/www/html/volumes
      - /var/run/docker.sock:/var/run/docker.sock
      - ./:/var/www/html
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/app
      - DOCKER_HOST=unix:///var/run/docker.sock
    networks:
      - traefik
    privileged: true
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.automation-webhook.rule=Host(`webhook.bwserver.com.br`) || Host(`localhost`)"
      - "traefik.http.routers.automation-webhook.entrypoints=web"
      - "traefik.http.services.automation-webhook.loadbalancer.server.port=80"
    restart: unless-stopped

networks:
  traefik:
    external: true