version: '3.8'

services:
  {{CONTAINER_NAME}}:
    image: davidsongomes/evolution-api:v2.1.1
    container_name: {{CONTAINER_NAME}}
    restart: unless-stopped
    environment:
      - SERVER_TYPE=https
      - SERVER_URL=https://{{SUBDOMAIN}}
      - CORS_ORIGIN=*
      - CORS_METHODS=GET,POST,PUT,DELETE
      - CORS_CREDENTIALS=true
      - LOG_LEVEL=ERROR
      - LOG_COLOR=true
      - DEL_INSTANCE=false
      - DATABASE_ENABLED=true
      - DATABASE_CONNECTION_URI=file:./db/database.db
      - DATABASE_CONNECTION_CLIENT_NAME=evolution_v2
      - REDIS_ENABLED=false
      - RABBITMQ_ENABLED=false
      - WEBSOCKET_ENABLED=false
      - WA_BUSINESS_TOKEN_WEBHOOK=evolution
      - WA_BUSINESS_URL=https://graph.facebook.com
      - WA_BUSINESS_VERSION=v20.0
      - WA_BUSINESS_LANGUAGE=pt_BR
      - WEBHOOK_GLOBAL_ENABLED=false
      - CONFIG_SESSION_PHONE_CLIENT=Evolution API
      - CONFIG_SESSION_PHONE_NAME=Chrome
      - QRCODE_LIMIT=30
      - AUTHENTICATION_TYPE=apikey
      - AUTHENTICATION_API_KEY={{API_KEY}}
      - AUTHENTICATION_EXPOSE_IN_FETCH_INSTANCES=true
      - LANGUAGE=en
    volumes:
      - {{CONTAINER_NAME}}_instances:/evolution/instances
      - {{CONTAINER_NAME}}_store:/evolution/store
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.{{CONTAINER_NAME}}.entrypoints=http"
      - "traefik.http.routers.{{CONTAINER_NAME}}.rule=Host(`{{SUBDOMAIN}}`)"
      - "traefik.http.middlewares.{{CONTAINER_NAME}}-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.{{CONTAINER_NAME}}.middlewares={{CONTAINER_NAME}}-https-redirect"
      - "traefik.http.routers.{{CONTAINER_NAME}}-secure.entrypoints=https"
      - "traefik.http.routers.{{CONTAINER_NAME}}-secure.rule=Host(`{{SUBDOMAIN}}`)"
      - "traefik.http.routers.{{CONTAINER_NAME}}-secure.tls=true"
      - "traefik.http.routers.{{CONTAINER_NAME}}-secure.tls.certresolver=cloudflare"
      - "traefik.http.services.{{CONTAINER_NAME}}.loadbalancer.server.port=8080"
      - "traefik.docker.network=traefik"
    deploy:
      resources:
        limits:
          cpus: '{{VCPU}}'
          memory: {{MEMORY}}M
        reservations:
          cpus: '0.1'
          memory: 256M

volumes:
  {{CONTAINER_NAME}}_instances:
  {{CONTAINER_NAME}}_store:

networks:
  traefik:
    external: true
