version: '3.8'

services:
  {{CONTAINER_NAME}}:
    image: n8nio/n8n:latest
    container_name: {{CONTAINER_NAME}}
    restart: unless-stopped
    environment:
      - N8N_HOST={{SUBDOMAIN}}
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - WEBHOOK_URL=https://{{SUBDOMAIN}}
      - GENERIC_TIMEZONE=America/Sao_Paulo
      - N8N_METRICS=true
      - QUEUE_BULL_REDIS_HOST=redis
      - CACHE_REDIS_HOST=redis
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE={{CONTAINER_NAME}}_db
      - DB_POSTGRESDB_USER={{CONTAINER_NAME}}_user
      - DB_POSTGRESDB_PASSWORD={{DB_PASSWORD}}
    volumes:
      - {{CONTAINER_NAME}}_data:/home/node/.n8n
    networks:
      - traefik
      - {{CONTAINER_NAME}}_internal
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.{{CONTAINER_NAME}}.entrypoints=http"
      - "traefik.http.routers.{{CONTAINER_NAME}}.rule=Host(`{{SUBDOMAIN}}`)"
      - "traefik.http.middlewares.{{CONTAINER_NAME}}-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.{{CONTAINER_NAME}}.middlewares={{CONTAINER_NAME}}-https-redirect"
      - "traefik.http.routers.{{CONTAINER_NAME}}-secure.entrypoints=https"
      - "traefik.http.routers.{{CONTAINER_NAME}}-secure.rule=Host(`{{SUBDOMAIN}}`)"
      - "traefik.http.routers.{{CONTAINER_NAME}}-secure.tls=true"
      - "traefik.http.routers.{{CONTAINER_NAME}}-secure.tls.certresolver=cloudflare"
      - "traefik.http.services.{{CONTAINER_NAME}}.loadbalancer.server.port=5678"
      - "traefik.docker.network=traefik"
    deploy:
      resources:
        limits:
          cpus: '{{VCPU}}'
          memory: {{MEMORY}}M
        reservations:
          cpus: '0.1'
          memory: 128M

  postgres:
    image: postgres:15
    container_name: {{CONTAINER_NAME}}_postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB={{CONTAINER_NAME}}_db
      - POSTGRES_USER={{CONTAINER_NAME}}_user
      - POSTGRES_PASSWORD={{DB_PASSWORD}}
    volumes:
      - {{CONTAINER_NAME}}_postgres:/var/lib/postgresql/data
    networks:
      - {{CONTAINER_NAME}}_internal

  redis:
    image: redis:7-alpine
    container_name: {{CONTAINER_NAME}}_redis
    restart: unless-stopped
    networks:
      - {{CONTAINER_NAME}}_internal

volumes:
  {{CONTAINER_NAME}}_data:
  {{CONTAINER_NAME}}_postgres:

networks:
  traefik:
    external: true
  {{CONTAINER_NAME}}_internal:
    driver: bridge
