services:
  evoapi-{{UNIQUE_ID}}:
    image: davidsongomes/evolution-api:latest
    container_name: evoapi-{{UNIQUE_ID}}
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - SERVER_TYPE=http
      - SERVER_PORT=8080
      - CORS_ORIGIN=*
      - CORS_METHODS=POST,GET,PUT,DELETE
      - CORS_CREDENTIALS=true
      - LOG_LEVEL=ERROR
      - LOG_COLOR=true
      - LOG_BAILEYS=error
      - DEL_INSTANCE=false
      - PROVIDER_ENABLED=false
      - PROVIDER_HOST=127.0.0.1
      - PROVIDER_PORT=5432
      - PROVIDER_PREFIX=evolution
      - DATABASE_ENABLED=false
      - DATABASE_CONNECTION_URI=mongodb://root:root@mongodb:27017/evolution?authSource=admin&readPreference=primary&ssl=false&directConnection=true
      - DATABASE_CONNECTION_DB_PREFIX_NAME=evolution
      - REDIS_ENABLED=false
      - REDIS_URI=redis://redis:6379
      - REDIS_PREFIX_KEY=evolution
      - RABBITMQ_ENABLED=false
      - RABBITMQ_URI=amqp://guest:guest@rabbitmq:5672
      - SQS_ENABLED=false
      - WEBSOCKET_ENABLED=false
      - WEBSOCKET_GLOBAL_EVENTS=false
      - WA_BUSINESS_TOKEN_WEBHOOK=evolution
      - WA_BUSINESS_URL=https://graph.facebook.com
      - WA_BUSINESS_VERSION=v18.0
      - WA_BUSINESS_LANGUAGE=pt_BR
      - WEBHOOK_GLOBAL_URL=
      - WEBHOOK_GLOBAL_ENABLED=false
      - WEBHOOK_GLOBAL_WEBHOOK_BY_EVENTS=false
      - CONFIG_SESSION_PHONE_CLIENT=Evolution API
      - CONFIG_SESSION_PHONE_NAME=Chrome
      - QRCODE_LIMIT=30
      - AUTHENTICATION_TYPE=apikey
      - AUTHENTICATION_API_KEY=429683C4C977415CAAFCCE10F7D57E11
      - AUTHENTICATION_EXPOSE_IN_FETCH_INSTANCES=true
      - LANGUAGE=pt-BR
    volumes:
      - ./data/evolution_instances:/evolution/instances
      - ./data/evolution_store:/evolution/store
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.evoapi-{{UNIQUE_ID}}.rule=Host(`{{SUBDOMAIN}}.bwserver.com.br`)"
      - "traefik.http.routers.evoapi-{{UNIQUE_ID}}.entrypoints=web"
      - "traefik.http.services.evoapi-{{UNIQUE_ID}}.loadbalancer.server.port=8080"

networks:
  traefik:
    external: true
