services:
  {{CONTAINER_NAME}}:
    image: docker.n8n.io/n8nio/n8n:latest
    restart: unless-stopped
    environment:
      - N8N_HOST={{N8N_HOST}}
      - GENERIC_TIMEZONE=America/Sao_Paulo
      - TZ=America/Sao_Paulo
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_RUNNERS_ENABLED=true
    volumes:
      - type: bind
        source: {{VOLUME_PATH}}
        target: /home/node/.n8n
    networks:
      - automation-webhook
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: '{{CPU_LIMIT}}'
          memory: '{{MEMORY_LIMIT}}'
        reservations:
          cpus: 1
          memory: '512MB'
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
      labels:
        - traefik.enable=true
        - traefik.docker.network=automation-webhook
        - traefik.http.routers.{{CONTAINER_NAME}}.rule=Host(`{{N8N_HOST}}`)
        - traefik.http.routers.{{CONTAINER_NAME}}.entrypoints=web
        - traefik.http.routers.{{CONTAINER_NAME}}.middlewares={{CONTAINER_NAME}}-redirect
        - traefik.http.routers.{{CONTAINER_NAME}}-secure.rule=Host(`{{N8N_HOST}}`)
        - traefik.http.routers.{{CONTAINER_NAME}}-secure.entrypoints=websecure
        - traefik.http.routers.{{CONTAINER_NAME}}-secure.tls=true
        - traefik.http.routers.{{CONTAINER_NAME}}-secure.tls.certresolver={{CERT_RESOLVER}}
        - traefik.http.services.{{CONTAINER_NAME}}.loadbalancer.server.port=5678
        - traefik.http.middlewares.{{CONTAINER_NAME}}-redirect.redirectscheme.scheme=https
        - traefik.http.middlewares.{{CONTAINER_NAME}}-redirect.redirectscheme.permanent=true

networks:
  automation-webhook:
    external: true